config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  resources :donations

  resources :recipients do
    resources :category_records
  end

  resources :users, only: [:index, :destroy] do
    get :approve, on: :member
    get :remove_approval, on: :member
    get :toggle_admin, on: :member
  end

  namespace :api do
    resources :recipients, only: [:index]
  end
end

app/models/recipient.rb
class Recipient < ApplicationRecord
	has_many :donations
  has_many :category_records

  validates :name, presence: true, uniqueness: true

  def to_s
    name
  end

  def total_donations(options = {})
    if options[:year]
      sql = "'#{options[:year]}-01-01' <= date AND date <= '#{options[:year]}-12-31'"
      donations.where(sql).sum(:amount)
    else
      donations.sum(:amount)
    end
  end

  def categories_string
    category_records.map { |cr| colorize_category(cr.category) }.join(' ').html_safe
  end

  def destroyable?
    donations.empty?
  end

  def self.serialized_for_api
    all.map do |recipient|
      {
        id: recipient.id,
        name: recipient.name,
      }
    end
  end
end

app/controllers/api/recipients_controller.rb
class Api::RecipientsController < ApplicationController
  def index
    render json: Recipient.serialized_for_api.to_json
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :set_recipient, only: [:show, :edit, :update, :destroy]

  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.all.order(created_at: :desc)
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
    @donations = @recipient.donations.where(user: current_user).order(date: :desc)
  end

  # GET /recipients/new
  def new
    @recipient = Recipient.new
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(recipient_params)
    respond_to do |format|
      if @recipient.save
        if request.xhr?
          format.html
          format.json { render :show, status: :created, location: @recipient }
        else
          format.html { redirect_to @recipient, notice: 'Recipient was successfully created.' }
          format.json { render :show, status: :created, location: @recipient }
        end
      else
        if request.xhr?
          format.json { render json: @recipient.errors, status: :unprocessable_entity }
        else
          format.html { render :new }
          format.json { render json: @recipient.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        format.html { redirect_to @recipient, notice: 'Recipient was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipient }
      else
        format.html { render :edit }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient.destroy
    respond_to do |format|
      format.html { redirect_to recipients_url, notice: 'Recipient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient
      @recipient = Recipient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipient_params
      params.require(:recipient).permit(:name, :reasons_for_support, :url)
    end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form.html.erb
<% options ||= {} %>

<%= form_for(@recipient, options) do |f| %>
  <% if @recipient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipient.errors.count, "error") %> prohibited this recipient from being saved:</h2>

      <ul>
      <% @recipient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="grid-x grid-margin-x">
    <div class="small-6 cell">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="grid-x grid-margin-x">
    <div class="small-6 cell">
      <%= f.label :url %>
      <%= f.url_field :url %>
    </div>
  </div>

  <div class="grid-x grid-margin-x">
    <div class="small-6 cell">
      <%= f.label :reasons_for_support %>
      <%= f.text_area :reasons_for_support %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
<% end %>

app/views/recipients/edit.html.erb
<h1><%= t(".title") %></h1>

<%= render 'form' %>

<%= link_to t("defaults.show_link"), @recipient %> |
<%= link_to t("defaults.back_link"), recipients_path %>

app/views/recipients/index.html.erb
<h1><%= t(".title") %></h1>

<% if @recipients.any? %>
  <table id="recipients_table">
    <thead>
      <tr>
        <th><%= Recipient.human_attribute_name(:name) %></th>
        <th><%= Recipient.human_attribute_name(:total_donations) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @recipients.each do |recipient| %>
        <tr>
          <td><%= link_to recipient.name, recipient %></td>
          <td><%= number_to_currency recipient.total_donations %></td>
          <td><%= link_to t("defaults.show_link"), recipient %></td>
          <td><%= link_to t("defaults.edit_link"), edit_recipient_path(recipient) %></td>
          <td>
            <% if recipient.destroyable? %>
              <%= link_to t("defaults.destroy_link"), recipient, method: :delete, data: { confirm: t("defaults.destroy_confirm") } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <%= t("defaults.no_records", records: "recipients") %>
<% end %>

<br>

<%= link_to t("defaults.new_link", model: "Recipient"), new_recipient_path, class: "button" %>

app/views/recipients/new.html.erb
<h1><%= t(".title") %></h1>

<%= render 'form' %>

<%= link_to t("defaults.back_link"), recipients_path %>

app/views/recipients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to t("defaults.edit_link"), edit_recipient_path(@recipient) %> |
  <%= link_to t("defaults.back_link"), recipients_path %>
</p>

<p>
  <strong><%= Recipient.human_attribute_name(:name) %>:</strong>
  <%= @recipient.name %>
</p>

<p>
  <strong><%= Recipient.human_attribute_name(:url) %>:</strong>
  <%= link_to @recipient.url, @recipient.url if @recipient.url %>
</p>

<p>
  <strong><%= Recipient.human_attribute_name(:reasons_for_support) %>:</strong>
  <%= @recipient.reasons_for_support %>
</p>

<p>
  <strong><%= Recipient.human_attribute_name(:categories) %>:</strong>
  <%= colorize_categories(@recipient.category_records) %>
  <%= link_to t(".new_category_link"), [:new, @recipient, :category_record] %>
</p>

<p>
  <strong><%= t(".donations_table_header") %>:</strong>

  <%= render "donations/donations_table", donations: @donations %>
</p>