config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  resources :donations

  resources :recipients do
    resources :category_records
  end

  resources :users, only: [:index, :destroy] do
    get :approve, on: :member
    get :remove_approval, on: :member
    get :toggle_admin, on: :member
  end

  namespace :api do
    resources :recipients, only: [:index]
  end
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :recipient
  belongs_to :user

  validates_presence_of :amount, :recipient, :date, :status, :user
  validates :amount, numericality: true

  VALID_METHODS = %w{
    credit_card
    cash
    payment_app
    other
  }

  VALID_STATUSES = %w{
    planned
    completed
    acknowledged
  }

  def to_s
    "$#{amount} to #{recipient.name}"
  end

  def recipient_name=(recipient_name)
    self.recipient_id = Recipient.find_by(name: recipient_name).id
    @recipient_name = recipient_name
  end

  def recipient_name
    @recipient_name ||= recipient&.name
  end

  def self.method_select_options
    VALID_METHODS.map do |method|
      [Donation.human_attribute_name("method.#{method}"), method]
    end
  end

  def self.status_select_options
    VALID_STATUSES.map do |status|
      [Donation.human_attribute_name("status.#{status}"), status]
    end
  end

  def completed?
    %w(completed acknowledged).include? status
  end

  def year
    date.year
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.where(user: current_user).order(date: :desc)

    if params[:year] && params[:year] =~ /\A\d+\z/
      start_of_year = Date.new(params[:year].to_i)
      end_of_year = start_of_year.end_of_year
      @donations = @donations.where(date: start_of_year..end_of_year)
    else
      params.delete(:year)
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new(date: Date.today)
    @recipient = Recipient.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)
    @donation.user = current_user

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: "Donation was successfully recorded." }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: "Donation was successfully updated." }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url, notice: "Donation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_donation
    @donation = Donation.find(params[:id])
    render_404 unless @donation.user == current_user
  end

  def donation_params
    donation_params = params.require(:donation).permit(
      :amount,
      :recipient_name,
      :date,
      :method,
      :status,
    )
    donation_params[:amount]&.gsub!("$", "")
    donation_params
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
  def display_currency(amount)
    amount == 0 ? "-" : number_to_currency(amount)
  end
end

app/views/donations/_donations_table.html.erb
<div id="donations_table_container">
  <% if donations.any? %>
    <table id="donations_table">
      <thead>
        <tr>
          <th><%= Donation.human_attribute_name(:date) %></th>
          <th><%= Donation.human_attribute_name(:recipient) %></th>
          <th><%= Donation.human_attribute_name(:amount) %></th>
          <th><%= Donation.human_attribute_name(:status) %></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% donations.each do |donation| %>
          <tr>
            <td><%= donation.date.to_s(:long) %></td>
            <td><%= link_to donation.recipient, donation.recipient %></td>
            <td class="accounting"><%= display_currency donation.amount %></td>
            <td><%= donation.status %></td>
            <td><%= link_to t("defaults.show_link"), donation %></td>
            <td><%= link_to t("defaults.edit_link"), edit_donation_path(donation) %></td>
            <td><%= link_to t("defaults.destroy_link"), donation, method: :delete, data: { confirm: t("defaults.destroy_confirm") } %></td>
          </tr>
        <% end %>
        <tr>
          <td><strong>Total</strong></td>
          <td></td>
          <td class="accounting"><strong><%= display_currency donations.sum(:amount) %></strong></td>
          <th colspan="4"></th>
        </tr>
      </tbody>
    </table>
  <% else %>
    <%= t("defaults.no_records", records: "donations") %>
  <% end %>
</div>

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="grid-x grid-margin-x">
    <div class="small-6 cell">
      <%= f.label :amount %>
      <%= f.text_field :amount %>
    </div>
  </div>

  <div class="grid-x grid-margin-x">
    <div class="small-6 cell">
      <%= f.label :recipient_name %>
      <%= f.text_field :recipient_name, class: "typeahead" %>
    </div>
    <script>instantiateRecipientsTypeahead();</script>
  </div>

  <div class="grid-x grid-margin-x">
    <div class="small-6 cell">
      <%= f.label :date %>
      <%= f.date_field :date %>
    </div>
  </div>

  <div class="grid-x grid-margin-x">
    <div class="small-6 cell">
      <%= f.label :method %>
      <%= f.select :method, Donation.method_select_options %>
    </div>
  </div>

  <div class="grid-x grid-margin-x">
    <div class="small-6 cell">
      <%= f.label :status %>
      <%= f.select :status, Donation.status_select_options %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
<% end %>

<div class="modal fade" id="newRecipientModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add new recipient</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "recipients/form", options: {remote: true} %>
      </div>
    </div>
  </div>
</div>

app/views/donations/_index.html.erb
<% if donations.any? %>
  <table>
    <thead>
      <tr>
        <th><%= Donation.human_attribute_name(:recipient) %></th>
        <% this_year = Date.today.year  %>
        <% years = (this_year - 4..this_year) %>
        <% years.each do |year| %>
          <th class="accounting"><%= link_to year, donations_path(year: year) %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% totals = {} %>
      <% years.each { |year| totals[year] = 0 } %>

      <% donations.group_by(&:recipient).each do |recipient, recipient_donations| %>
        <tr>
          <td><%= link_to recipient, recipient %></td>

          <% years.each do |year| %>
            <% amount = recipient_donations.find_all { |d| d.year == year }.sum(&:amount) %>
            <td class="accounting"><%= display_currency(amount) %></td>
            <% totals[year] += amount %>
          <% end %>
        </tr>
      <% end %>

      <tr>
        <td><strong><%= t('.total') %></strong></td>

        <% years.each do |year| %>
          <td class="accounting"><strong><%= number_to_currency totals[year] %></strong></td>
        <% end %>
      </tr>
    </tbody>
  </table>
<% else %>
  <%= t("defaults.no_records", records: "donations") %>
<% end %>

app/views/donations/_year_index.html.erb
<p><%= link_to t('.show_more_years_link'), donations_path, class: 'button tiny' if params[:year] %></p>

<%= render "donations_table", donations: donations %>

app/views/donations/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('defaults.show_link'), @donation %> |
<%= link_to t('defaults.back_link'), donations_path %>

app/views/donations/index.html.erb
<h1><%= "#{params[:year]}" if params[:year] %> <%= t('.title') %></h1>

<% if params[:year] %>
  <%= render 'year_index', donations: @donations, year: params[:year] %>
<% else %>
  <%= render 'index', donations: @donations %>
<% end %>

<br>

<%= link_to t("defaults.new_link", model: Donation), new_donation_path, class: 'button' %>

app/views/donations/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('defaults.back_link'), donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Donation.human_attribute_name(:amount) %>:</strong>
  <%= number_to_currency @donation.amount %>
</p>

<p>
  <strong><%= Donation.human_attribute_name(:recipient) %>:</strong>
  <%= @donation.recipient %>
</p>

<p>
  <strong><%= Donation.human_attribute_name(:date) %>:</strong>
  <%= @donation.date.to_s(:long) %>
</p>

<p>
  <strong><%= Donation.human_attribute_name(:method) %>:</strong>
  <%= @donation.method.try(:humanize) %>
</p>

<p>
  <strong><%= Donation.human_attribute_name(:status) %>:</strong>
  <%= @donation.status.humanize %>
</p>

<%= link_to t("defaults.edit_link"), edit_donation_path(@donation) %> |
<%= link_to t("defaults.back_link"), donations_path %>