config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  resources :donations

  resources :recipients do
    resources :category_records
  end

  resources :users, only: [:index, :destroy] do
    get :approve, on: :member
    get :remove_approval, on: :member
    get :toggle_admin, on: :member
  end

  namespace :api do
    resources :recipients, only: [:index]
  end
end

app/models/category_record.rb
class CategoryRecord < ApplicationRecord
  belongs_to :recipient

  validates_presence_of :category

  def to_s
    category
  end
end

app/controllers/category_records_controller.rb
class CategoryRecordsController < ApplicationController
  before_action :load_parents
  before_action :set_category_record, only: [:show, :edit, :update, :destroy]

  # GET /category_records
  # GET /category_records.json
  def index
    # @search = CategoryRecord.search(params[:search])
    # @category_records = @search.all   # load all matching records
    if params[:category]
      @category_records = CategoryRecord.where(category: params[:category])
    else
      @category_records = CategoryRecord.all
    end
  end

  # GET /category_records/1
  # GET /category_records/1.json
  def show
  end

  # GET /category_records/new
  def new
    @category_record = CategoryRecord.new
  end

  # GET /category_records/1/edit
  def edit
  end

  # POST /category_records
  # POST /category_records.json
  def create
    @category_record = CategoryRecord.new(category_record_params)

    respond_to do |format|
      if @category_record.save
        format.html { redirect_to @recipient, notice: 'Category record was successfully created.' }
        format.json { render :show, status: :created, location: @category_record }
      else
        format.html { render :new }
        format.json { render json: @category_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_records/1
  # PATCH/PUT /category_records/1.json
  def update
    respond_to do |format|
      if @category_record.update(category_record_params)
        format.html { redirect_to @category_record, notice: 'Category record was successfully updated.' }
        format.json { render :show, status: :ok, location: @category_record }
      else
        format.html { render :edit }
        format.json { render json: @category_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_records/1
  # DELETE /category_records/1.json
  def destroy
    @category_record.destroy
    respond_to do |format|
      format.html { redirect_to category_records_url, notice: 'Category record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category_record
    @category_record = CategoryRecord.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_record_params
    params.require(:category_record).permit(:recipient_id, :category)
  end

  def load_parents
    @recipient = Recipient.find(params[:recipient_id])
  end
end

app/helpers/category_records_helper.rb
module
  CategoryRecordsHelper

  def colorize_categories(category_records)
    category_records.map { |cr| colorize_category(cr) }.join(' ').html_safe
    # colors.map { |cr| colorize_category(cr) }.join(' ').html_safe
  end

  def colorize_category(category_record)
    color = colors[string_to_int(category_record.category) % (colors.count - 1)]
    # color = category_record
    "<span style='background-color: #{color}; padding: 3px'>#{category_record}</span>".html_safe
  end

  def string_to_int(s)
    x = 0
    (0..(s.length - 1)).each do |i|
      x += s[i].ord
    end
    x
  end

  def colors
    %w(
      Aqua
      Aquamarine
      BlueViolet
      BurlyWood
      CadetBlue
      Chocolate
      Coral
      CornflowerBlue
      Crimson
      DarkCyan
      DarkGoldenRod
      DarkGray
      DarkKhaki
      DarkOrange
      DarkOrchid
      DarkSalmon
      DarkSeaGreen
      DarkTurquoise
      DarkViolet
      DeepPink
      DeepSkyBlue
      DodgerBlue
      FireBrick
      ForestGreen
      Fuchsia
      Gold
      GoldenRod
      GreenYellow
      HotPink
      IndianRed
      Khaki
      Lavender
      LawnGreen
      LemonChiffon
      LightBlue
      LightCoral
      LightCyan
      LightGoldenRodYellow
      LightGray
      LightGreen
      LightPink
      LightSalmon
      LightSeaGreen
      LightSkyBlue
      LightSlateGray
      LightSteelBlue
      Lime
      LimeGreen
      Magenta
      MediumAquaMarine
      MediumOrchid
      MediumPurple
      MediumSeaGreen
      MediumSlateBlue
      MediumSpringGreen
      MediumTurquoise
      MediumVioletRed
      Moccasin
      Olive
      Orange
      OrangeRed
      Orchid
      PaleGoldenRod
      PaleGreen
      PaleTurquoise
      PaleVioletRed
      PeachPuff
      Peru
      Pink
      Plum
      PowderBlue
      Red
      RosyBrown
      RoyalBlue
      SaddleBrown
      Salmon
      SandyBrown
      SeaGreen
      Sienna
      Silver
      SkyBlue
      SlateBlue
      SpringGreen
      SteelBlue
      Tan
      Thistle
      Tomato
      Turquoise
      Violet
      Wheat
      Yellow
      YellowGreen
    )
 end
end

app/views/category_records/_form.html.erb
<%= form_for([@recipient, @category_record]) do |f| %>
  <% if @category_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category_record.errors.count, "error") %> prohibited this category_record from being saved:</h2>

      <ul>
      <% @category_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :recipient_id, value: @recipient.id %>

  <div class="grid-x grid-margin-x">
    <div class="small-6 cell">
      <%= f.text_field :category %>
    </div>
  </div>

  <% if CategoryRecord.count > 0 %>
    <p><%= t(".existing_categories") %></p>
    <p><%= colorize_categories CategoryRecord.select(:category).group(:category) %></p>
  <% end %>

  <div class="actions">
    <%= f.submit t("helpers.submit.create", model: "Category"), class: "button" %>
  </div>
<% end %>

app/views/category_records/edit.html.erb
<h1>Editing category_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @category_record %> |
<%= link_to 'Back', category_records_path %>

app/views/category_records/index.html.erb
<h1>Listing category records</h1>

<p><%= link_to 'Show all', category_records_path if params[:category] %></p>
<table>
  <thead>
    <tr>
      <th>Recipient</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @category_records.each do |category_record| %>
      <tr>
        <td><%= link_to category_record.recipient, category_record.recipient %></td>
        <td><%= link_to category_record.category, category_records_path(category: category_record.category) %></td>
        <td><%= link_to 'Show', category_record %></td>
        <td><%= link_to 'Edit', edit_category_record_path(category_record) %></td>
        <td><%= link_to 'Destroy', category_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category record', new_category_record_path %>

app/views/category_records/new.html.erb
<h1><%= t(".title") %></h1>

<%= render 'form' %>

<%= link_to t("defaults.back_link"), @recipient %>

app/views/category_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipient:</strong>
  <%= @category_record.recipient %>
</p>

<p>
  <strong>Category:</strong>
  <%= @category_record.category %>
</p>

<%= link_to 'Edit', edit_category_record_path(@category_record) %> |
<%= link_to 'Back', category_records_path %>