config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  resources :donations

  resources :recipients do
    resources :category_records
  end

  resources :users, only: [:index, :destroy] do
    get :approve, on: :member
    get :remove_approval, on: :member
    get :toggle_admin, on: :member
  end

  namespace :api do
    resources :recipients, only: [:index]
  end
end

app/views/layouts/_bottom_bar.html.erb
<footer class="footer">
  <div class="grid-x full-width">
    <div class="cell text-center">
      <%= link_to("https://github.com/lbraun/thanksgiving") do %>
        <%= image_tag("GitHub-Mark-32px.png") %>
      <% end %>
    </div>
  </div>
</footer>

app/views/layouts/_top_bar.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li><%= link_to t("defaults.home_link"), root_path %></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li class="divider"></li>

      <% if current_user %>
        <% if current_user.approved? %>
          <% if current_user.admin? %>
            <li><%= link_to t("defaults.users_link"), users_path %></li>
            <li class="divider"></li>
          <% end %>

          <li><%= link_to t("defaults.donations_link"), donations_path %></li>
          <li class="divider"></li>

          <li><%= link_to t("defaults.recipients_link"), recipients_path %></li>
          <li class="divider"></li>
        <% end %>

        <li><%= link_to "#{t("defaults.sign_out")} #{current_user.name}", signout_path, id: "sign_out" %></li>
      <% else %>
        <li><%= link_to t("defaults.sign_in_with_google_link"), "/auth/google_oauth2", id: "sign_in" %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Thanksgiving" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%#= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/top_bar' %>

    <main class="main-content">
      <div class="grid-x grid-padding-x">
        <div class="small-12 cell">
          <%= yield %>
        </div>
      </div>
    </main>

    <%= render 'layouts/bottom_bar' %>
  </body>
</html>